import type {IncomingMessage,ServerResponse} from 'node:http';
import {createHash,randomUUID,timingSafeEqual} from 'node:crypto';
import {basename,dirname,extname,join} from 'node:path';
import {OfficeStore,EventError} from './store.js';
import {RemoteClients} from './remoteClients.js';
import {OfficeHistory} from './history.js';
import {DeviceTokenStore,type DeviceProvider} from './deviceTokens.js';
import {AuthError,AuthService,type AuthUser} from './auth.js';
import {OfficeRegistry,type OfficeInfo} from './offices.js';
import type {OfficeAgent,OfficeSnapshot} from '../src/officeModel.js';

type Options={token?:string;localHealth?:()=>unknown;historyPath?:string;deviceTokensPath?:string;authPath?:string;officesPath?:string};
type Authorization={kind:'master'|'device'|'user';officeId:string;user?:AuthUser};
type Runtime={officeId:string;store:OfficeStore;history:OfficeHistory;clients:Set<ServerResponse>;remote:RemoteClients;codex:RemoteClients;publish:()=>void;};

const activityLabels:Record<string,string>={working:'Sedang bekerja',thinking:'Sedang berpikir',waiting:'Menunggu jawaban',error:'Perlu perhatian',idle:'Siaga',done:'Pekerjaan selesai'};
function publicAgent(agent:OfficeAgent){const {machineId:_machineId,machineLabel:_machineLabel,bridgeVersion:_bridgeVersion,projectKey:_projectKey,projectName:_projectName,...safe}=agent;const labels:Record<string,string>={edit:'Mengubah file',command:'Menjalankan perintah',test:'Menjalankan tes',research:'Membaca referensi',thinking:'Sedang berpikir',waiting:'Menunggu jawaban',error:'Perlu perhatian',generic:activityLabels[agent.status]||'Bekerja'};return {...safe,task:agent.activityCode?labels[agent.activityCode]:(activityLabels[agent.status]||'Bekerja')};}
function publicSnapshot(snapshot:OfficeSnapshot):OfficeSnapshot{return {...snapshot,agents:snapshot.agents.map(publicAgent)};}

export function createOfficeApi(options:Options={}){
 const offices=new OfficeRegistry(options.officesPath),deviceTokens=new DeviceTokenStore(options.deviceTokensPath),auth=new AuthService({dataPath:options.authPath});
 const runtimes=new Map<string,Runtime>();let started=false;
 function historyPath(officeId:string){if(!options.historyPath||officeId==='default')return options.historyPath;const extension=extname(options.historyPath),stem=basename(options.historyPath,extension);return join(dirname(options.historyPath),`${stem}-${officeId}${extension||'.json'}`);}
 function runtimeFor(officeId:string){const existing=runtimes.get(officeId);if(existing)return existing;const store=new OfficeStore(randomUUID()),history=new OfficeHistory(historyPath(officeId)),clients=new Set<ServerResponse>();let runtime!:Runtime;const snapshot=()=>`event: office\ndata: ${JSON.stringify(publicSnapshot(store.get()))}\n\n`;const publish=()=>{const payload=snapshot();for(const client of clients)if(!client.destroyed)client.write(payload);};const remote=new RemoteClients(store,publish),codex=new RemoteClients(store,publish,Date.now,'codex');runtime={officeId,store,history,clients,remote,codex,publish};runtimes.set(officeId,runtime);if(started){remote.start();codex.start();}return runtime;}
 const defaultRuntime=runtimeFor('default');
 function json(res:ServerResponse,status:number,body:unknown){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(body));}
 function authorized(req:IncomingMessage):Authorization|null {const header=req.headers.authorization??'';if(header.startsWith('Bearer ')){const presented=header.slice(7),presentedHash=createHash('sha256').update(presented).digest();if(options.token&&timingSafeEqual(presentedHash,createHash('sha256').update(options.token).digest()))return {kind:'master',officeId:'default'};const device=deviceTokens.find(presented);if(device)return {kind:'device',officeId:device.officeId};}const user=auth.getUser(req);if(user){const office=offices.ensureForUser(user.id,user.displayName);return {kind:'user',officeId:office.id,user};}return null;}
 function allowedOrigin(req:IncomingMessage){if(!req.headers.origin)return true;try{const origin=new URL(req.headers.origin);return ['http:','https:'].includes(origin.protocol)&&origin.host===req.headers.host;}catch{return false;}}
 function officeFromRef(ref:string|undefined){if(!ref||ref==='default')return offices.get('default');return offices.get(ref)||offices.getBySlug(ref);}
 function canView(req:IncomingMessage,office:OfficeInfo){if(office.publicEnabled)return true;const identity=authorized(req);return Boolean(identity&&identity.officeId===office.id&&(identity.kind==='master'||identity.kind==='user'));}
 function publicOffice(office:OfficeInfo){const runtime=runtimeFor(office.id),snapshot=runtime.store.get(),active=snapshot.agents.filter(agent=>agent.status!=='done'),health=[runtime.remote.getHealth().lastHeartbeatAt,runtime.codex.getHealth().lastHeartbeatAt];return {id:office.id,slug:office.slug,displayName:office.displayName,activeAgents:active.length,totalAgents:snapshot.agents.length,agents:active.slice(0,8).map(agent=>{const safe=publicAgent(agent);return {id:safe.id,name:safe.name,role:safe.role,team:safe.team,status:safe.status,avatarStyle:safe.avatarStyle,activity:safe.task};}),updatedAt:Math.max(office.updatedAt,...health)};}
 async function readJson(req:IncomingMessage){const chunks:Buffer[]=[];let bytes=0;for await(const chunk of req){bytes+=Buffer.byteLength(chunk);if(bytes>65536)throw new EventError('Request body exceeds 64 KiB.',413);chunks.push(Buffer.from(chunk));}try{return JSON.parse(Buffer.concat(chunks).toString('utf8')) as unknown;}catch{throw new EventError('Invalid JSON.');}}
 function stream(res:ServerResponse,runtime:Runtime){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive','X-Accel-Buffering':'no'});res.write('retry: 2000\n\n'+'event: office\ndata: '+JSON.stringify(publicSnapshot(runtime.store.get()))+'\n\n');runtime.clients.add(res);const timer=setInterval(()=>{if(!res.destroyed)res.write(': heartbeat\n\n');},15000);timer.unref();res.once('close',()=>{clearInterval(timer);runtime.clients.delete(res)});}
 async function middleware(req:IncomingMessage,res:ServerResponse,next:()=>void){
  const url=new URL(req.url||'/',`http://${req.headers.host||'office.local'}`),path=url.pathname;if(!path.startsWith('/api/')){next();return;}
  if(req.method==='GET'&&path==='/api/auth/me'){const user=auth.getUser(req);const office=user?offices.ensureForUser(user.id,user.displayName):undefined;json(res,200,{authenticated:Boolean(user),user:user?{id:user.id,provider:user.provider,login:user.login,displayName:user.displayName}:null,office:office?{id:office.id,slug:office.slug,displayName:office.displayName,publicEnabled:office.publicEnabled}:null});return;}
  if((req.method==='POST'&&path==='/api/auth/register')||(req.method==='POST'&&path==='/api/auth/login')){if(!allowedOrigin(req)){json(res,403,{ok:false,error:'Cross-origin writes are not allowed.'});return;}if(!req.headers['content-type']?.startsWith('application/json')){json(res,415,{ok:false,error:'Use Content-Type: application/json.'});return;}try{const body=await readJson(req) as Record<string,unknown>;(path.endsWith('/register')?auth.register.bind(auth):auth.login.bind(auth))(req,res,body);}catch(error){json(res,error instanceof AuthError||error instanceof EventError?error.status:500,{ok:false,error:error instanceof Error?error.message:'Authentication failed.'});}return;}
  if(req.method==='POST'&&path==='/api/auth/logout'){if(!allowedOrigin(req)){json(res,403,{ok:false,error:'Cross-origin writes are not allowed.'});return;}auth.logout(req,res);return;}
  if(path.startsWith('/api/offices/')&&req.method==='PATCH'){const officeId=decodeURIComponent(path.slice('/api/offices/'.length)),identity=authorized(req);if(!identity||identity.kind!=='user'||identity.officeId!==officeId){json(res,403,{ok:false,error:'Only the office owner can change these settings.'});return;}if(!allowedOrigin(req)){json(res,403,{ok:false,error:'Cross-origin writes are not allowed.'});return;}if(!req.headers['content-type']?.startsWith('application/json')){json(res,415,{ok:false,error:'Use Content-Type: application/json.'});return;}try{const body=await readJson(req) as Record<string,unknown>,patch:{slug?:string;displayName?:string;publicEnabled?:boolean}={};if(body.slug!==undefined){if(typeof body.slug!=='string'||body.slug.length>48)throw new EventError('slug must be a string up to 48 characters.');patch.slug=body.slug;}if(body.displayName!==undefined){if(typeof body.displayName!=='string'||body.displayName.length>80)throw new EventError('displayName must be a string up to 80 characters.');patch.displayName=body.displayName;}if(body.publicEnabled!==undefined){if(typeof body.publicEnabled!=='boolean')throw new EventError('publicEnabled must be boolean.');patch.publicEnabled=body.publicEnabled;}const office=offices.update(officeId,patch);if(!office)throw new EventError('Office not found.',404);json(res,200,{ok:true,office:{id:office.id,slug:office.slug,displayName:office.displayName,publicEnabled:office.publicEnabled}});}catch(error){json(res,error instanceof EventError?error.status:409,{ok:false,error:error instanceof Error?error.message:'Could not update office.'});}return;}
  if(req.method==='GET'&&path==='/api/health'){json(res,200,{ok:true,revision:defaultRuntime.store.get().revision});return;}
  if(req.method==='GET'&&path==='/api/public/offices'){json(res,200,{items:offices.listPublic().map(publicOffice)});return;}
  if(path.startsWith('/api/public/offices/')){const isStream=path.endsWith('/stream'),slug=decodeURIComponent(path.slice('/api/public/offices/'.length,isStream?-'/stream'.length:undefined)),office=offices.getBySlug(slug);if(!office||!office.publicEnabled){json(res,404,{ok:false,error:'Public office not found.'});return;}const runtime=runtimeFor(office.id);if(isStream&&req.method==='GET'){stream(res,runtime);return;}if(req.method==='GET'){json(res,200,{office:publicOffice(office),snapshot:publicSnapshot(runtime.store.get())});return;}json(res,405,{ok:false,error:'Method not allowed.'});return;}
  if(req.method==='GET'&&path==='/api/state'){const office=officeFromRef(url.searchParams.get('office')??undefined);if(!office){json(res,404,{ok:false,error:'Office not found.'});return;}if(!canView(req,office)){json(res,401,{ok:false,error:'Owner login required.'});return;}json(res,200,publicSnapshot(runtimeFor(office.id).store.get()));return;}
  const readRoute=path==='/api/integrations/hermes'||path==='/api/integrations/codex'||path==='/api/integrations'||path==='/api/history'||path==='/api/stream';
  if(req.method==='GET'&&readRoute){const office=officeFromRef(url.searchParams.get('office')??undefined);if(!office){json(res,404,{ok:false,error:'Office not found.'});return;}if(!canView(req,office)){json(res,401,{ok:false,error:'Owner login required.'});return;}const runtime=runtimeFor(office.id);if(path==='/api/stream'){stream(res,runtime);return;}if(path==='/api/integrations/hermes'){json(res,200,{...runtime.remote.getHealth(),clientsList:runtime.remote.getRegistry(),...(options.localHealth?{local:options.localHealth()}: {})});return;}if(path==='/api/integrations/codex'){json(res,200,{...runtime.codex.getHealth(),clientsList:runtime.codex.getRegistry()});return;}if(path==='/api/integrations'){json(res,200,{serverNow:Date.now(),clients:[...runtime.remote.getRegistry(),...runtime.codex.getRegistry()]});return;}const items=runtime.history.list(Number(url.searchParams.get('limit')||50),Number(url.searchParams.get('cursor')||0));json(res,200,{...items,items:items.items.map(({machineLabel:_machineLabel,...entry})=>entry)});return;}
  if(path==='/api/device-tokens'){
   const identity=authorized(req),officeId=identity?.kind==='user'?identity.officeId:'default';if(req.method==='GET'){if(!identity||!['master','user'].includes(identity.kind)){json(res,401,{ok:false,error:'Owner login or admin token required.'});return;}json(res,200,{items:deviceTokens.list(officeId)});return;}if(req.method!=='POST'){json(res,405,{ok:false,error:'Method not allowed.'});return;}if(!allowedOrigin(req)){json(res,403,{ok:false,error:'Cross-origin writes are not allowed.'});return;}if(!identity||!['master','user'].includes(identity.kind)){json(res,401,{ok:false,error:'Owner login or admin token required.'});return;}if(!req.headers['content-type']?.startsWith('application/json')){json(res,415,{ok:false,error:'Use Content-Type: application/json.'});return;}
   try{const body=await readJson(req) as Record<string,unknown>,label=typeof body.label==='string'?body.label:'',kind=(body.provider==='hermes'||body.provider==='codex'||body.provider==='both'?body.provider:'both') as DeviceProvider;if(!label.trim()||label.length>48)throw new EventError('label must be 1–48 characters.');const created=deviceTokens.create(label,kind,officeId);json(res,201,{ok:true,id:created.info.id,label:created.info.label,provider:created.info.provider,officeId:created.info.officeId,createdAt:created.info.createdAt,token:created.token});}catch(error){json(res,error instanceof EventError?error.status:500,{ok:false,error:error instanceof EventError?error.message:'Could not create device token.'});}return;
  }
  if(path==='/api/device-tokens/revoke'){
   const identity=authorized(req);if(req.method!=='POST'){json(res,405,{ok:false,error:'Method not allowed.'});return;}if(!allowedOrigin(req)){json(res,403,{ok:false,error:'Cross-origin writes are not allowed.'});return;}if(!identity||!['master','user'].includes(identity.kind)){json(res,401,{ok:false,error:'Owner login or admin token required.'});return;}if(!req.headers['content-type']?.startsWith('application/json')){json(res,415,{ok:false,error:'Use Content-Type: application/json.'});return;}
   try{const body=await readJson(req) as Record<string,unknown>,officeId=identity.kind==='user'?identity.officeId:'default';if(typeof body.id!=='string'||!deviceTokens.belongsTo(body.id,officeId)||!deviceTokens.revoke(body.id))throw new EventError('Device token not found or already revoked.',404);json(res,200,{ok:true,id:body.id});}catch(error){json(res,error instanceof EventError?error.status:500,{ok:false,error:error instanceof EventError?error.message:'Could not revoke device token.'});}return;
  }
  if(req.method!=='POST'||!['/api/events','/api/agents','/api/hermes/heartbeat','/api/codex/heartbeat'].includes(path)){json(res,404,{ok:false,error:'Unknown endpoint.'});return;}
  if(!allowedOrigin(req)){json(res,403,{ok:false,error:'Cross-origin writes are not allowed.'});return;}if(!options.token&&path.endsWith('/heartbeat')){json(res,503,{ok:false,error:'Configure OFFICE_API_TOKEN to receive remote clients.'});return;}
  const identity=authorized(req);if(!identity||!['master','device'].includes(identity.kind)){json(res,401,{ok:false,error:'Invalid API token.'});return;}if(!req.headers['content-type']?.startsWith('application/json')){json(res,415,{ok:false,error:'Use Content-Type: application/json.'});return;}
  const runtime=runtimeFor(identity.officeId);
  try{const body=await readJson(req);if(path.endsWith('/heartbeat')){const result=(path==='/api/codex/heartbeat'?runtime.codex:runtime.remote).ingest(body);const source=path==='/api/codex/heartbeat'?'codex':'hermes';for(const agent of runtime.store.get().agents.filter(item=>item.provider===source))runtime.history.update(agent,agent.status!=='done',agent.status==='done'?(agent.task.includes('terputus')?'disconnected':'completed'):'observed');json(res,200,{ok:true,...result,revision:runtime.store.get().revision,officeId:runtime.officeId});return;}const result=runtime.store.apply(path==='/api/agents'?{type:'agent.upsert',agent:body}:body);if(!result.duplicate){const snap=runtime.store.get(),changed=snap.agents.find(a=>a.id===((body as any)?.agent?.id||(body as any)?.id));if(changed)runtime.history.update(changed,changed.status!=='done',changed.status==='done'?'completed':'observed');runtime.publish();}json(res,200,{ok:true,...result});}
  catch(error){json(res,error instanceof EventError?error.status:500,{ok:false,error:error instanceof EventError?error.message:'Server could not process this event.'});}
 }
 return {store:defaultRuntime.store,remote:defaultRuntime.remote,codex:defaultRuntime.codex,history:defaultRuntime.history,deviceTokens,auth,offices,runtimeFor,publish:defaultRuntime.publish,middleware,start:()=>{started=true;for(const runtime of runtimes.values()){runtime.remote.start();runtime.codex.start()}},close:()=>{started=false;for(const runtime of runtimes.values()){runtime.remote.stop();runtime.codex.stop();for(const client of runtime.clients)client.end();runtime.clients.clear();}}};
}
