import {createServer,type Server} from 'node:http';
import {afterEach,it,expect} from 'vitest';
import {createOfficeApi} from './api';
const token='a'.repeat(64),resources:Array<{server:Server;api:ReturnType<typeof createOfficeApi>}>=[];
afterEach(async()=>{for(const {server,api} of resources.splice(0)){api.close();server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}});
async function setup(){const api=createOfficeApi({token});const server=createServer((req,res)=>{void api.middleware(req,res,()=>{res.writeHead(404);res.end();});});resources.push({api,server});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();if(!address||typeof address==='string')throw new Error();return {api,url:`http://127.0.0.1:${address.port}`};}
const body={version:1,clientId:'machine',producerId:'producer',sequence:1,sessions:[{agent:{id:'hermes-'+'a'.repeat(24),name:'remote-project',role:'Hermes · Terminal',team:'research',status:'working',task:'Menyusun jawaban'},active:true,updatedAt:1}]};
it('accepts authenticated Codex sessions and exposes independent integration health',async()=>{
 const f=await setup(),payload={...body,sessions:body.sessions.map(s=>({...s,agent:{...s.agent,id:'codex-'+'b'.repeat(24),role:'Codex · Desktop'}}))};
 const headers={'Content-Type':'application/json',Authorization:'Bearer '+token};
 expect((await fetch(f.url+'/api/codex/heartbeat',{method:'POST',headers,body:JSON.stringify(payload)})).status).toBe(200);
 expect(await (await fetch(f.url+'/api/integrations/codex')).json()).toMatchObject({clients:1,activeSessions:1});
 expect(await (await fetch(f.url+'/api/integrations/hermes')).json()).toMatchObject({clients:0,activeSessions:0});
 expect((await fetch(f.url+'/api/hermes/heartbeat',{method:'POST',headers,body:JSON.stringify(payload)})).status).toBe(400);
 expect((await fetch(f.url+'/api/codex/heartbeat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})).status).toBe(401);
});
it('returns provider registry metadata and closes a lightweight history interval',async()=>{
 const f=await setup(),headers={'Content-Type':'application/json',Authorization:'Bearer '+token},codexBody={...body,sessions:body.sessions.map(session=>({...session,agent:{...session.agent,id:'codex-'+'c'.repeat(24),role:'Codex · Desktop'}}))};
 const working=await fetch(f.url+'/api/codex/heartbeat',{method:'POST',headers,body:JSON.stringify(codexBody)});expect(working.status).toBe(200);
 const done={...codexBody,sequence:2,sessions:codexBody.sessions.map(session=>({...session,active:false,updatedAt:2,agent:{...session.agent,status:'done',task:'Selesai'}}))};
 expect((await fetch(f.url+'/api/codex/heartbeat',{method:'POST',headers,body:JSON.stringify(done)})).status).toBe(200);
 expect(await (await fetch(f.url+'/api/integrations')).json()).toMatchObject({clients:[{provider:'codex',machineLabel:'Mesin machin'}]});
 const history=await (await fetch(f.url+'/api/history')).json();expect(history.items[0]).toMatchObject({name:'remote-project',reason:'completed'});
});
it('requires bearer authentication for writes and leaves reads available to the dashboard',async()=>{const f=await setup();for(const route of ['/api/agents','/api/hermes/heartbeat']){const res=await fetch(f.url+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});expect(res.status).toBe(401);}expect(f.api.store.get().agents).toHaveLength(0);expect((await fetch(f.url+'/api/health')).status).toBe(200);const accepted=await fetch(f.url+'/api/hermes/heartbeat',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)});expect(accepted.status).toBe(200);expect(f.api.store.get().agents[0].name).toBe('remote-project');});
it('creates, uses, lists and revokes a device token without exposing it in the registry',async()=>{const f=await setup(),master={'Content-Type':'application/json',Authorization:'Bearer '+token};expect((await fetch(f.url+'/api/device-tokens',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:'unauthorized'})})).status).toBe(401);const createdResponse=await fetch(f.url+'/api/device-tokens',{method:'POST',headers:master,body:JSON.stringify({label:'Mac kerja',provider:'both'})});expect(createdResponse.status).toBe(201);const created=await createdResponse.json() as {id:string;token:string};expect(created.token).toMatch(/^[a-f0-9]{64}$/);const device={'Content-Type':'application/json',Authorization:'Bearer '+created.token};expect((await fetch(f.url+'/api/hermes/heartbeat',{method:'POST',headers:device,body:JSON.stringify(body)})).status).toBe(200);const listed=await (await fetch(f.url+'/api/device-tokens',{headers:{Authorization:'Bearer '+token}})).json() as {items:Array<Record<string,unknown>>};expect(listed.items[0]).toMatchObject({id:created.id,label:'Mac kerja',provider:'both'});expect(listed.items[0]).not.toHaveProperty('token');expect((await fetch(f.url+'/api/device-tokens/revoke',{method:'POST',headers:master,body:JSON.stringify({id:created.id})})).status).toBe(200);expect((await fetch(f.url+'/api/hermes/heartbeat',{method:'POST',headers:device,body:JSON.stringify({...body,sequence:2})})).status).toBe(401);});
it('streams a remote update to the browser and rejects malformed or oversized writes',async()=>{const f=await setup();const stream=await fetch(f.url+'/api/stream');expect(stream.headers.get('content-type')).toBe('text/event-stream');const reader=stream.body!.getReader();await reader.read();await fetch(f.url+'/api/hermes/heartbeat',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)});const update=await reader.read();expect(new TextDecoder().decode(update.value)).toContain('remote-project');await reader.cancel();const headers={'Content-Type':'application/json',Authorization:'Bearer '+token};expect((await fetch(f.url+'/api/hermes/heartbeat',{method:'POST',headers,body:'{broken'})).status).toBe(400);expect((await fetch(f.url+'/api/agents',{method:'POST',headers,body:'x'.repeat(66000)})).status).toBe(413);});
