import {createServer,type Server} from 'node:http';
import {afterEach,it,expect} from 'vitest';
import {createOfficeApi} from './api';
const token='a'.repeat(64),resources:Array<{server:Server;api:ReturnType<typeof createOfficeApi>}>=[];
afterEach(async()=>{for(const {server,api} of resources.splice(0)){api.close();server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}});
async function setup(){const api=createOfficeApi({token});const server=createServer((req,res)=>{void api.middleware(req,res,()=>{res.writeHead(404);res.end();});});resources.push({api,server});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();if(!address||typeof address==='string')throw new Error();return {api,url:`http://127.0.0.1:${address.port}`};}
const body={version:1,clientId:'machine',producerId:'producer',sequence:1,sessions:[{agent:{id:'hermes-'+'a'.repeat(24),name:'remote-project',role:'Hermes · Terminal',team:'research',status:'working',task:'Menyusun jawaban'},active:true,updatedAt:1}]};
it('requires bearer authentication for writes and leaves reads available to the dashboard',async()=>{const f=await setup();for(const route of ['/api/agents','/api/hermes/heartbeat']){const res=await fetch(f.url+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});expect(res.status).toBe(401);}expect(f.api.store.get().agents).toHaveLength(0);expect((await fetch(f.url+'/api/health')).status).toBe(200);const accepted=await fetch(f.url+'/api/hermes/heartbeat',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)});expect(accepted.status).toBe(200);expect(f.api.store.get().agents[0].name).toBe('remote-project');});
it('streams a remote update to the browser and rejects malformed or oversized writes',async()=>{const f=await setup();const stream=await fetch(f.url+'/api/stream');expect(stream.headers.get('content-type')).toBe('text/event-stream');const reader=stream.body!.getReader();await reader.read();await fetch(f.url+'/api/hermes/heartbeat',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)});const update=await reader.read();expect(new TextDecoder().decode(update.value)).toContain('remote-project');await reader.cancel();const headers={'Content-Type':'application/json',Authorization:'Bearer '+token};expect((await fetch(f.url+'/api/hermes/heartbeat',{method:'POST',headers,body:'{broken'})).status).toBe(400);expect((await fetch(f.url+'/api/agents',{method:'POST',headers,body:'x'.repeat(66000)})).status).toBe(413);});
