import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {afterEach,it,expect} from 'vitest';
import {HermesBridge} from './hermesBridge';
import {OfficeStore} from './store';
const directories:string[]=[];
afterEach(async()=>{for(const directory of directories.splice(0))await rm(directory,{recursive:true,force:true});});
async function setup(){const directory=await mkdtemp(join(tmpdir(),'office-hermes-'));directories.push(directory);let now=100000,alive=true,published=0;const store=new OfficeStore('test'),bridge=new HermesBridge(store,()=>{published++;},{directory,now:()=>now,isAlive:()=>alive});return {directory,store,bridge,time:(value:number)=>{now=value;},die:()=>{alive=false;},published:()=>published};}
const id='hermes-'+'a'.repeat(24);
const row=(updatedAt=100000,active=true)=>({agent:{id,name:'my-project',role:'Hermes · Terminal',team:'research',status:active?'working':'done',task:'Menggunakan tool: terminal',progress:null},active,updatedAt});
async function write(directory:string,sessions:unknown[],heartbeatAt=100000,file='123-abc.json'){await writeFile(join(directory,file),JSON.stringify({version:1,pid:123,heartbeatAt,sessions}));}
it('deduplicates heartbeats, merges one session across processes, and replays after server restart',async()=>{const f=await setup();await write(f.directory,[row()]);await f.bridge.poll();expect(f.store.get().agents).toHaveLength(1);expect(f.store.get().agents[0].name).toBe('my-project');const revision=f.store.get().revision;await write(f.directory,[row()],100001);await f.bridge.poll();expect(f.store.get().revision).toBe(revision);await write(f.directory,[row(100001,false)],100001,'124-def.json');await f.bridge.poll();expect(f.store.get().agents).toHaveLength(1);expect(f.store.get().agents[0].status).toBe('done');const restored=new OfficeStore();await new HermesBridge(restored,()=>{},{directory:f.directory,now:()=>100002,isAlive:()=>true}).poll();expect(restored.get().agents[0].status).toBe('done');});
it('sends dead or stale sessions home and removes them after the departure grace period',async()=>{const f=await setup();await write(f.directory,[row()]);await f.bridge.poll();f.die();f.time(100001);await f.bridge.poll();expect(f.store.get().agents[0]).toMatchObject({status:'done',task:'Session tidak aktif'});f.time(190002);await f.bridge.poll();expect(f.store.get().agents).toHaveLength(0);await f.bridge.poll();expect(f.store.get().agents).toHaveLength(0);const stale=await setup();await write(stale.directory,[row()]);await stale.bridge.poll();stale.time(136000);await stale.bridge.poll();expect(stale.store.get().agents[0].status).toBe('done');});
it('handles missing files, invalid rows, and capacity without removing manual API agents',async()=>{const f=await setup();f.store.apply({type:'agent.upsert',agent:{id:'manual',name:'Manual'}});await write(f.directory,[{...row(),agent:{...row().agent,status:'invalid'}},row()]);await writeFile(join(f.directory,'999-bad.json'),'broken');await f.bridge.poll();expect(f.store.get().agents).toHaveLength(2);await rm(join(f.directory,'123-abc.json'));await f.bridge.poll();expect(f.store.get().agents.find(a=>a.id===id)?.status).toBe('done');f.time(191000);await f.bridge.poll();expect(f.store.get().agents.map(a=>a.id)).toEqual(['manual']);});
it('resumes the same person and accepts newer work after a previous producer died',async()=>{const f=await setup();await write(f.directory,[row(100000,false)]);await f.bridge.poll();expect(f.store.get().agents[0].status).toBe('done');f.time(101000);await write(f.directory,[row(101000)],101000,'124-def.json');await f.bridge.poll();expect(f.store.get().agents).toHaveLength(1);expect(f.store.get().agents[0]).toMatchObject({id,status:'working'});expect(f.bridge.getHealth().activeSessions).toBe(1);});
