import {it,expect} from 'vitest';
import {RemoteHermes} from './remoteHermes';
import {OfficeStore} from './store';
const row=(updatedAt=100,active=true)=>({agent:{id:'hermes-'+'a'.repeat(24),name:'project',role:'Hermes · Terminal',team:'research',status:active?'working':'done',task:'Menggunakan tool: terminal'},active,updatedAt});
const packet=(clientId='machine-a',producerId='process-a',sequence=1,sessions=[row()])=>({version:1,clientId,producerId,sequence,sessions});
function setup(){let now=100000;const store=new OfficeStore();let publishes=0;const remote=new RemoteHermes(store,()=>{publishes++;},()=>now);return {store,remote,time:(t:number)=>{now=t;},publishes:()=>publishes};}
it('namespaces sessions by machine, deduplicates same-session processes, and rejects old packets',()=>{const f=setup();f.remote.ingest(packet());f.remote.ingest(packet('machine-b'));expect(f.store.get().agents).toHaveLength(2);f.remote.ingest(packet('machine-a','process-b',1,[row(101)]));expect(f.store.get().agents).toHaveLength(2);const before=f.store.get();expect(f.remote.ingest(packet()).duplicate).toBe(true);expect(f.store.get()).toEqual(before);expect(f.remote.getHealth()).toMatchObject({clients:2,producers:3,activeSessions:2});});
it('uses server leases despite clock skew, sends disconnected people home, and removes stale records once',()=>{const f=setup();f.remote.ingest(packet('machine-a','process-a',1,[row(9_000_000_000_000)]));expect(f.store.get().agents[0].status).toBe('working');f.time(135001);f.remote.reconcile();expect(f.store.get().agents[0].status).toBe('done');f.time(225002);f.remote.reconcile();expect(f.store.get().agents).toHaveLength(0);f.remote.reconcile();expect(f.store.get().agents).toHaveLength(0);});
it('heartbeats do not replay completion, and a resumed session keeps its avatar ID',()=>{const f=setup();f.remote.ingest(packet());const id=f.store.get().agents[0].id;f.remote.ingest(packet('machine-a','process-a',2,[row(101,false)]));const revision=f.store.get().revision;f.time(110000);f.remote.ingest(packet('machine-a','process-a',3,[row(101,false)]));expect(f.store.get().revision).toBe(revision);f.time(190001);f.remote.ingest(packet('machine-a','process-a',4,[row(101,false)]));expect(f.store.get().agents).toHaveLength(0);f.time(190002);f.remote.ingest(packet('machine-a','process-a',5,[row(102)]));expect(f.store.get().agents[0]).toMatchObject({id,status:'working'});});
it('validates full snapshots atomically and tolerates a disappeared session without touching manual agents',()=>{const f=setup();f.store.apply({type:'agent.upsert',agent:{id:'manual'}});expect(()=>f.remote.ingest({...packet(),sessions:[row(),{...row(),active:'bad'}]})).toThrow();expect(f.store.get().agents).toHaveLength(1);f.remote.ingest(packet());f.remote.ingest(packet('machine-a','process-a',2,[]));expect(f.store.get().agents.find(a=>a.id!=='manual')?.status).toBe('done');f.time(190001);f.remote.reconcile();expect(f.store.get().agents.map(a=>a.id)).toEqual(['manual']);});
