import {useEffect,useMemo,useState} from 'react';
import {Activity,ChevronRight,Clock,Filter,History,Leaf,Pause,Play,Server,SlidersHorizontal,Sparkles,Users,Wifi,X} from 'lucide-react';
import {roomInfo,statusInfo} from './officeModel';
import {useOffice,type OfficeClient,type OfficeFilters} from './useOffice';
import Office from './components/Office';

type Panel='none'|'people'|'connections'|'history';
const reasonLabel:Record<string,string>={completed:'Selesai',aborted:'Dihentikan',disconnected:'Terputus',observed:'Terpantau'};
function relativeTime(timestamp:number){if(!timestamp)return 'belum ada heartbeat';const seconds=Math.max(0,Math.round((Date.now()-timestamp)/1000));if(seconds<2)return 'baru saja';if(seconds<60)return `${seconds} detik lalu`;const minutes=Math.round(seconds/60);return `${minutes} menit lalu`;}
function clientStatus(client:OfficeClient){if(!client.connected)return 'Terputus';return Date.now()-client.lastHeartbeatAt>20000?'Terlambat':'Terhubung';}

export default function App(){
 const {snapshot,mode,changeMode,connected,paused,setPaused,clients,history,filters,setFilters,projects,machines}=useOffice();
 const [selected,setSelected]=useState<string|null>(null),[panel,setPanel]=useState<Panel>('none'),[reducedMotion,setReducedMotion]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);
 const agent=snapshot.agents.find(a=>a.id===selected),working=snapshot.agents.filter(a=>a.status==='working'||a.status==='thinking').length;
 const togglePanel=(next:Panel)=>setPanel(current=>current===next?'none':next);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){setSelected(null);setPanel('none')}if(event.code==='Space'&&mode==='demo'&&!['INPUT','BUTTON','SELECT'].includes((event.target as HTMLElement)?.tagName)){event.preventDefault();setPaused(value=>!value)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[mode,setPaused]);
 const clearFilters=()=>setFilters({project:'',machine:'',provider:''});
 const filtersActive=Object.values(filters).some(Boolean);
 return <main className="office-app">
  <header className="office-header"><div className="office-brand"><span><Leaf size={22}/></span><div><strong>little office</strong><small>{snapshot.title}</small></div></div>
   <div className="office-header-actions"><div className="mode-switch" aria-label="Sumber tampilan"><button className={mode==='demo'?'selected':''} onClick={()=>{changeMode('demo');setSelected(null)}}>Demo</button><button className={mode==='api'?'selected':''} onClick={()=>{changeMode('api');setSelected(null)}}>Live API</button></div>
    <span className={`connection ${mode==='api'&&!connected?'offline':''}`}><i/>{mode==='demo'?'Simulasi':connected?'Server terhubung':'Menghubungkan…'}</span>
    <button className={`header-tool ${panel==='connections'?'active':''}`} onClick={()=>togglePanel('connections')} aria-label="Koneksi client"><Wifi size={16}/><span>{mode==='demo'?'Koneksi':`${clients.filter(c=>c.connected).length} mesin`}</span></button>
    <button className={`header-tool ${panel==='people'?'active':''}`} onClick={()=>togglePanel('people')} aria-label="Daftar agent"><Users size={16}/><span>{snapshot.agents.length} agent</span></button>
   </div></header>
  <section className="office-window"><Office view={{snapshot,paused,selected,reducedMotion}} onSelect={setSelected}/>
   <div className="office-caption"><span><i/>{working} agent bekerja</span><span className="caption-separator">·</span><span>{filtersActive?`${snapshot.agents.length} ditampilkan · filter aktif`:mode==='demo'?'Animasi contoh':'Status dari script lu'}</span></div>
   {mode==='api'&&!snapshot.agents.length&&<div className="waiting-card"><Leaf size={26}/><h2>{filtersActive?'Tidak ada yang cocok.':'Kantor siap.'}</h2><p>{filtersActive?'Hapus filter untuk melihat agent lain.':clients.some(c=>c.connected)?'Semua sedang istirahat. Client tetap terhubung.':'Menunggu agent terhubung.'}</p>{filtersActive&&<button onClick={clearFilters}>Hapus filter</button>}</div>}
   {agent&&<div className="agent-card" aria-label={`Detail ${agent.name}`}><button className="card-close" aria-label="Tutup detail" onClick={()=>setSelected(null)}><X size={15}/></button><div className="card-agent-heading"><span className={`agent-portrait ${agent.team}`} style={{backgroundImage:`url(/assets/portrait-${agent.team}.png)`}}/><div><h2>{agent.name}</h2><p>{agent.role}<span> · {roomInfo[agent.team].name}</span></p></div></div><div className={`agent-state ${agent.status}`}><i/>{statusInfo[agent.status].label}</div><p className="agent-task">{agent.task||'Belum ada aktivitas.'}</p>{agent.machineLabel&&<p className="agent-meta"><Server size={11}/> {agent.provider||'manual'} · {agent.machineLabel}</p>}{agent.progress!==undefined&&<div className="agent-progress"><i style={{width:`${agent.progress*100}%`}}/><span>{Math.round(agent.progress*100)}%</span></div>}{agent.parentId&&<p className="parent-label">Subagent dari {snapshot.agents.find(a=>a.id===agent.parentId)?.name||agent.parentId}</p>}</div>}
   {panel!=='none'&&<aside className="office-panel" aria-label={panel==='people'?'Daftar agent':panel==='connections'?'Koneksi client':'Riwayat aktivitas'}>
    <div className="panel-heading"><div><small>{panel==='people'?'PENGHUNI KANTOR':panel==='connections'?'STATUS CLIENT':'AKTIVITAS TERAKHIR'}</small><h2>{panel==='people'?'Daftar agent':panel==='connections'?'Koneksi':'Riwayat'}</h2></div><button aria-label="Tutup panel" onClick={()=>setPanel('none')}><X size={18}/></button></div>
    {panel==='people'&&<><div className="filter-row"><Filter size={14}/><strong>Filter tampilan</strong>{filtersActive&&<button onClick={clearFilters}>Hapus</button>}</div><div className="filter-grid"><label>Project<select value={filters.project} onChange={event=>setFilters({...filters,project:event.target.value})}><option value="">Semua project</option>{projects.map(project=><option key={project}>{project}</option>)}</select></label><label>Mesin<select value={filters.machine} onChange={event=>setFilters({...filters,machine:event.target.value})}><option value="">Semua mesin</option>{machines.map(machine=><option key={machine}>{machine}</option>)}</select></label><label>Provider<select value={filters.provider} onChange={event=>setFilters({...filters,provider:event.target.value})}><option value="">Semua provider</option><option value="codex">Codex</option><option value="hermes">Hermes</option><option value="manual">Manual</option></select></label></div><div className="panel-list">{snapshot.agents.map(a=><button className="panel-agent" key={a.id} onClick={()=>{setSelected(a.id);setPanel('none')}}><span className={`agent-portrait ${a.team}`} style={{backgroundImage:`url(/assets/portrait-${a.team}.png)`}}/><span><strong>{a.name}</strong><small>{a.projectName||a.name} · {a.role}</small></span><span className={`roster-status ${a.status}`}><i/>{statusInfo[a.status].label}</span><ChevronRight size={14}/></button>)}{!snapshot.agents.length&&<p className="empty-roster">Tidak ada agent yang cocok.</p>}</div></>}
    {panel==='connections'&&<div className="panel-list connection-list">{mode==='demo'&&<p className="panel-note">Demo tidak mengirim heartbeat client.</p>}{clients.map(client=><ClientRow key={`${client.provider}:${client.clientId}`} client={client}/>)}{mode==='api'&&!clients.length&&<p className="empty-roster">Belum ada client terdeteksi.</p>}</div>}
    {panel==='history'&&<div className="panel-list history-list">{history.map(entry=><div className="history-row" key={entry.id}><span className="history-icon"><Clock size={13}/></span><div><strong>{entry.name}</strong><small>{entry.projectName||entry.name} · {entry.provider||'manual'} · {entry.machineLabel||'Mesin lokal'}</small></div><span><b>{reasonLabel[entry.reason]||entry.reason}</b><small>{Math.round(entry.durationMs/60000)} mnt</small></span></div>)}{!history.length&&<p className="empty-roster">Belum ada riwayat.</p>}</div>}
   </aside>}
  </section>
  <footer className="office-footer"><span>Klik agent untuk melihat aktivitas <span>✦</span></span><div><button className={panel==='history'?'active':''} aria-label="Riwayat aktivitas" onClick={()=>togglePanel('history')}><History size={14}/><span>Riwayat</span></button><button className={reducedMotion?'active':''} aria-label={reducedMotion?'Aktifkan animasi':'Kurangi animasi'} title="Kurangi gerakan" onClick={()=>setReducedMotion(value=>!value)}><Sparkles size={15}/><span>{reducedMotion?'Gerakan minimal':'Cozy animation'}</span></button>{mode==='demo'&&<button aria-label={paused?'Lanjutkan demo':'Jeda demo'} onClick={()=>setPaused(value=>!value)}>{paused?<Play size={14}/>:<Pause size={14}/>}<span>{paused?'Lanjutkan':'Jeda'}</span></button>}</div></footer>
 </main>;
}

function ClientRow({client}:{client:OfficeClient}){const status=clientStatus(client);return <div className="client-row"><span className={`client-dot ${client.connected?'online':'offline'}`}><Wifi size={13}/></span><div><strong>{client.provider==='codex'?'Codex':'Hermes'} · {client.machineLabel}</strong><small>{client.activeSessions} session aktif · heartbeat {relativeTime(client.lastHeartbeatAt)}</small></div><span className={`client-state ${client.connected?'online':''}`}>{status}</span></div>}
