import {useEffect,useMemo,useState} from 'react';
import {Activity,Check,ChevronRight,Clock,Copy,Filter,History,KeyRound,Leaf,Pause,Play,Plus,Server,SlidersHorizontal,Sparkles,Users,Wifi,X} from 'lucide-react';
import {roomInfo,statusInfo} from './officeModel';
import {useOffice,type OfficeClient,type OfficeFilters} from './useOffice';
import Office from './components/Office';

type Panel='none'|'people'|'connections'|'history';
type DeviceProvider='both'|'hermes'|'codex';
const reasonLabel:Record<string,string>={completed:'Selesai',aborted:'Dihentikan',disconnected:'Terputus',observed:'Terpantau'};
function relativeTime(timestamp:number){if(!timestamp)return 'belum ada heartbeat';const seconds=Math.max(0,Math.round((Date.now()-timestamp)/1000));if(seconds<2)return 'baru saja';if(seconds<60)return `${seconds} detik lalu`;const minutes=Math.round(seconds/60);return `${minutes} menit lalu`;}
function clientStatus(client:OfficeClient){if(!client.connected)return 'Terputus';return Date.now()-client.lastHeartbeatAt>20000?'Terlambat':'Terhubung';}

export default function App(){
 const {snapshot,mode,changeMode,connected,paused,setPaused,clients,history,filters,setFilters,projects,machines}=useOffice();
 const [selected,setSelected]=useState<string|null>(null),[panel,setPanel]=useState<Panel>('none'),[addAgentOpen,setAddAgentOpen]=useState(false),[reducedMotion,setReducedMotion]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);
 const agent=snapshot.agents.find(a=>a.id===selected),detailAgent=agent?.parentId?snapshot.agents.find(a=>a.id===agent.parentId):agent,children=detailAgent?snapshot.agents.filter(a=>a.parentId===detailAgent.id):[],working=snapshot.agents.filter(a=>a.status==='working'||a.status==='thinking').length;
 const togglePanel=(next:Panel)=>setPanel(current=>current===next?'none':next);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){if(addAgentOpen)setAddAgentOpen(false);else{setSelected(null);setPanel('none')}}if(event.code==='Space'&&mode==='demo'&&!['INPUT','BUTTON','SELECT'].includes((event.target as HTMLElement)?.tagName)){event.preventDefault();setPaused(value=>!value)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[addAgentOpen,mode,setPaused]);
 const clearFilters=()=>setFilters({project:'',machine:'',provider:''});
 const filtersActive=Object.values(filters).some(Boolean);
 return <main className="office-app">
  <header className="office-header"><div className="office-brand"><span><Leaf size={22}/></span><div><strong>NekOffice</strong></div></div>
   <div className="office-header-actions"><div className="mode-switch" aria-label="Sumber tampilan"><button className={mode==='demo'?'selected':''} onClick={()=>{changeMode('demo');setSelected(null)}}>Demo</button><button className={mode==='api'?'selected':''} onClick={()=>{changeMode('api');setSelected(null)}}>Live API</button></div>
    <span className={`connection ${mode==='api'&&!connected?'offline':''}`}><i/>{mode==='demo'?'Simulasi':connected?'Server terhubung':'Menghubungkan…'}</span>
    <button className={`header-tool ${panel==='connections'?'active':''}`} onClick={()=>togglePanel('connections')} aria-label="Koneksi client"><Wifi size={16}/><span>{mode==='demo'?'Koneksi':`${clients.filter(c=>c.connected).length} mesin`}</span></button>
    <button className={`header-tool ${panel==='people'?'active':''}`} onClick={()=>togglePanel('people')} aria-label="Daftar agent"><Users size={16}/><span>{snapshot.agents.length} agent</span></button>
   </div></header>
  <section className="office-window"><Office view={{snapshot,paused,selected,reducedMotion}} onSelect={setSelected}/>
   <div className="office-caption"><span><i/>{working} agent bekerja</span>{(filtersActive||mode==='demo')&&<><span className="caption-separator">·</span><span>{filtersActive?`${snapshot.agents.length} ditampilkan · filter aktif`:'Animasi contoh'}</span></>}</div>
   {mode==='api'&&!snapshot.agents.length&&<div className="waiting-card"><Leaf size={26}/><h2>{filtersActive?'Tidak ada yang cocok.':'Kantor siap.'}</h2><p>{filtersActive?'Hapus filter untuk melihat agent lain.':clients.some(c=>c.connected)?'Semua sedang istirahat. Client tetap terhubung.':'Menunggu agent terhubung.'}</p>{filtersActive&&<button onClick={clearFilters}>Hapus filter</button>}</div>}
   {agent&&detailAgent&&<div className="agent-card" aria-label={'Detail '+detailAgent.name}>
    <button className="card-close" aria-label="Tutup detail" onClick={()=>setSelected(null)}><X size={15}/></button>
    <div className="card-agent-heading"><span className={'agent-portrait '+detailAgent.team} style={{backgroundImage:'url(/assets/portrait-'+detailAgent.team+'.png)'}}/><div><h2>{detailAgent.name}</h2><p>{detailAgent.role}<span> · {roomInfo[detailAgent.team].name}</span></p></div></div>
    {agent.parentId&&<p className="parent-label">Subagent terpilih: {agent.name}</p>}
    <div className={'agent-state '+agent.status}><i/>{statusInfo[agent.status].label}</div>
    <p className="agent-task">{agent.task||'Belum ada aktivitas.'}</p>
    {(detailAgent.machineLabel||agent.machineLabel)&&<p className="agent-meta"><Server size={11}/> {detailAgent.provider||agent.provider||'manual'} · {detailAgent.machineLabel||agent.machineLabel}</p>}
    {agent.progress!==undefined&&<div className="agent-progress"><i style={{width:(agent.progress*100)+'%'}}/><span>{Math.round(agent.progress*100)}%</span></div>}
    {children.length>0&&<div className="group-detail"><div className="group-summary"><strong>{children.length} subagent</strong><span>{children.filter(child=>child.status!=='done').length} aktif</span></div><div className="child-list">{children.map(child=><button className={'child-item '+(child.id===agent.id?'selected':'')} key={child.id} onClick={()=>setSelected(child.id)}><span className={'agent-portrait '+child.team} style={{backgroundImage:'url(/assets/portrait-'+child.team+'.png)'}}/><span><strong>{child.name}</strong><small>{child.task||'Belum ada aktivitas.'}</small></span><span className={'roster-status '+child.status}><i/>{statusInfo[child.status].label}</span></button>)}</div></div>}
   </div>}
   {panel!=='none'&&<aside className="office-panel" aria-label={panel==='people'?'Daftar agent':panel==='connections'?'Koneksi client':'Riwayat aktivitas'}>
    <div className="panel-heading"><div><small>{panel==='people'?'PENGHUNI KANTOR':panel==='connections'?'STATUS CLIENT':'AKTIVITAS TERAKHIR'}</small><h2>{panel==='people'?'Daftar agent':panel==='connections'?'Koneksi':'Riwayat'}</h2></div><div className="panel-heading-actions">{panel==='people'&&<button className="add-agent-button" aria-label="Tambah agent" onClick={()=>setAddAgentOpen(true)}><Plus size={14}/><span>Tambah agent</span></button>}<button aria-label="Tutup panel" onClick={()=>setPanel('none')}><X size={18}/></button></div></div>
    {panel==='people'&&<><div className="filter-row"><Filter size={14}/><strong>Filter tampilan</strong>{filtersActive&&<button onClick={clearFilters}>Hapus</button>}</div><div className="filter-grid"><label>Project<select value={filters.project} onChange={event=>setFilters({...filters,project:event.target.value})}><option value="">Semua project</option>{projects.map(project=><option key={project}>{project}</option>)}</select></label><label>Mesin<select value={filters.machine} onChange={event=>setFilters({...filters,machine:event.target.value})}><option value="">Semua mesin</option>{machines.map(machine=><option key={machine}>{machine}</option>)}</select></label><label>Provider<select value={filters.provider} onChange={event=>setFilters({...filters,provider:event.target.value})}><option value="">Semua provider</option><option value="codex">Codex</option><option value="hermes">Hermes</option><option value="manual">Manual</option></select></label></div><div className="panel-list">{snapshot.agents.map(a=><button className="panel-agent" key={a.id} onClick={()=>{setSelected(a.id);setPanel('none')}}><span className={`agent-portrait ${a.team}`} style={{backgroundImage:`url(/assets/portrait-${a.team}.png)`}}/><span><strong>{a.name}</strong><small>{a.projectName||a.name} · {a.role}</small></span><span className={`roster-status ${a.status}`}><i/>{statusInfo[a.status].label}</span><ChevronRight size={14}/></button>)}{!snapshot.agents.length&&<p className="empty-roster">Tidak ada agent yang cocok.</p>}</div></>}
    {panel==='connections'&&<div className="panel-list connection-list">{mode==='demo'&&<p className="panel-note">Demo tidak mengirim heartbeat client.</p>}{clients.map(client=><ClientRow key={`${client.provider}:${client.clientId}`} client={client}/>)}{mode==='api'&&!clients.length&&<p className="empty-roster">Belum ada client terdeteksi.</p>}</div>}
    {panel==='history'&&<div className="panel-list history-list">{history.map(entry=><div className="history-row" key={entry.id}><span className="history-icon"><Clock size={13}/></span><div><strong>{entry.name}</strong><small>{entry.projectName||entry.name} · {entry.provider||'manual'} · {entry.machineLabel||'Mesin lokal'}</small></div><span><b>{reasonLabel[entry.reason]||entry.reason}</b><small>{Math.round(entry.durationMs/60000)} mnt</small></span></div>)}{!history.length&&<p className="empty-roster">Belum ada riwayat.</p>}</div>}
   </aside>}
   {addAgentOpen&&<DeviceTokenModal onClose={()=>setAddAgentOpen(false)}/>}
  </section>
  <footer className="office-footer"><span>Klik agent untuk melihat aktivitas <span>✦</span></span><div><button className={panel==='history'?'active':''} aria-label="Riwayat aktivitas" onClick={()=>togglePanel('history')}><History size={14}/><span>Riwayat</span></button><button className={reducedMotion?'active':''} aria-label={reducedMotion?'Aktifkan animasi':'Kurangi animasi'} title="Kurangi gerakan" onClick={()=>setReducedMotion(value=>!value)}><Sparkles size={15}/><span>{reducedMotion?'Gerakan minimal':'Cozy animation'}</span></button>{mode==='demo'&&<button aria-label={paused?'Lanjutkan demo':'Jeda demo'} onClick={()=>setPaused(value=>!value)}>{paused?<Play size={14}/>:<Pause size={14}/>}<span>{paused?'Lanjutkan':'Jeda'}</span></button>}</div></footer>
 </main>;
}

function ClientRow({client}:{client:OfficeClient}){const status=clientStatus(client);return <div className="client-row"><span className={`client-dot ${client.connected?'online':'offline'}`}><Wifi size={13}/></span><div><strong>{client.provider==='codex'?'Codex':'Hermes'} · {client.machineLabel}</strong><small>{client.activeSessions} session aktif · heartbeat {relativeTime(client.lastHeartbeatAt)}</small></div><span className={`client-state ${client.connected?'online':''}`}>{status}</span></div>}

function DeviceTokenModal({onClose}:{onClose:()=>void}){
 const [label,setLabel]=useState(''),[provider,setProvider]=useState<DeviceProvider>('both'),[adminToken,setAdminToken]=useState(''),[result,setResult]=useState<{id:string;token:string}|null>(null),[error,setError]=useState(''),[copied,setCopied]=useState<'markdown'|'token'|''>('');
 const hermesMarkdown=`## Hermes\n\n~~~sh\ngit clone git@github.com:yughoz/nekoffice.git\ncd nekoffice\ncp integrations/client.env.example .env\n# Isi LITTLE_OFFICE_API_TOKEN dengan token di atas\npython3 integrations/hermes/install_bridge.py --env-file .env\n~~~`,codexMarkdown=`## Codex\n\n~~~sh\npython3 integrations/codex/install.py --env-file .env --autostart\n~~~`,markdown=result?`# Nekoffice — ${label}\n\nServer:\n${window.location.origin}\n\nDevice token:\n${result.token}\n\n${provider==='hermes'?hermesMarkdown:provider==='codex'?codexMarkdown:hermesMarkdown+'\n\n'+codexMarkdown}`:'';
 const create=async()=>{setError('');if(!label.trim()){setError('Isi nama device dulu.');return;}if(!adminToken.trim()){setError('Masukkan kunci admin server untuk membuat token.');return;}try{const response=await fetch('/api/device-tokens',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${adminToken.trim()}`},body:JSON.stringify({label:label.trim(),provider})});const payload=await response.json() as {ok?:boolean;token?:string;id?:string;error?:string};if(!response.ok||!payload.ok||!payload.token||!payload.id)throw new Error(payload.error||'Server menolak pembuatan token.');setResult({id:payload.id,token:payload.token});setAdminToken('');}catch(cause){setError(cause instanceof Error?cause.message:'Tidak bisa membuat token.');}};
 const copy=async(kind:'markdown'|'token')=>{try{await navigator.clipboard.writeText(kind==='markdown'?markdown:result?.token||'');setCopied(kind);window.setTimeout(()=>setCopied(''),1800);}catch{setError('Clipboard tidak tersedia. Salin teks secara manual.');}};
 return <div className="token-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="token-modal" role="dialog" aria-modal="true" aria-labelledby="token-modal-title"><div className="token-modal-heading"><div><small>PAIRING DEVICE</small><h2 id="token-modal-title">Tambah agent</h2></div><button aria-label="Tutup tambah agent" onClick={onClose}><X size={18}/></button></div>{!result?<><p className="token-modal-intro">Buat token khusus untuk satu device. Hermes dan Codex di device yang sama bisa memakai token ini.</p><label className="token-field">Nama device<input autoFocus value={label} maxLength={48} placeholder="Mac kerja" onChange={event=>setLabel(event.target.value)}/></label><label className="token-field">Provider<select value={provider} onChange={event=>setProvider(event.target.value as DeviceProvider)}><option value="both">Hermes + Codex</option><option value="hermes">Hermes</option><option value="codex">Codex</option></select></label><label className="token-field">Kunci admin server<input type="password" value={adminToken} placeholder="Tidak disimpan" onChange={event=>setAdminToken(event.target.value)}/><small>Ini hanya dipakai untuk meminta token baru dan tidak dimasukkan ke Markdown.</small></label>{error&&<p className="token-error" role="alert">{error}</p>}<button className="token-primary" onClick={create}><KeyRound size={14}/>Buat token device</button></>:<><p className="token-success"><Check size={15}/>Token device berhasil dibuat untuk <strong>{label}</strong>.</p><div className="token-secret"><small>TOKEN DEVICE</small><code>{result.token}</code><button onClick={()=>copy('token')}>{copied==='token'?<Check size={14}/>:<Copy size={14}/>} {copied==='token'?'Tersalin':'Copy token'}</button></div><div className="markdown-preview"><div><small>MARKDOWN INSTALLASI</small><button onClick={()=>copy('markdown')}>{copied==='markdown'?<Check size={14}/>:<Copy size={14}/>} {copied==='markdown'?'Tersalin':'Copy Markdown'}</button></div><pre>{markdown}</pre></div><p className="token-note">Token ini tetap dipakai device tersebut sampai lu mencabutnya dari server.</p></>}</section></div>;
}
