import {useEffect,useState} from 'react';
import {ArrowRight,Leaf,LogIn,RefreshCw,Users,Wifi} from 'lucide-react';

type PublicOffice={id:string;slug:string;displayName:string;activeAgents:number;totalAgents:number;updatedAt:number;agents:Array<{id:string;name:string;role:string;activity:string}>};
function ago(timestamp:number){if(!timestamp)return 'belum ada aktivitas';const minutes=Math.max(0,Math.round((Date.now()-timestamp)/60000));return minutes<1?'baru saja':`${minutes} menit lalu`;}

export default function PublicLobby(){
 const [offices,setOffices]=useState<PublicOffice[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{try{const response=await fetch('/api/public/offices',{cache:'no-store'});if(!response.ok)throw new Error('Public Lobby belum tersedia.');const payload=await response.json() as {items?:PublicOffice[]};setOffices(payload.items||[]);setError('');}catch(cause){setError(cause instanceof Error?cause.message:'Tidak bisa memuat office.');}finally{setLoading(false)}};
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),10000);return()=>clearInterval(timer)},[]);
 return <main className="lobby-app"><header className="lobby-header"><a className="lobby-brand" href="/"><span><Leaf size={22}/></span><div><strong>little office</strong><small>Public Lobby</small></div></a><div className="lobby-actions"><span className="lobby-live"><i/>Live preview</span><a className="lobby-login" href="/?auth=login"><LogIn size={14}/>Masuk owner</a></div></header><section className="lobby-hero"><div><p className="eyebrow">NEKOFFICE LIVE</p><h1>Lihat agent bekerja.</h1><p>Contoh office yang memilih tampil publik. Prompt dan data pribadi tidak ditampilkan.</p></div><div className="lobby-count"><strong>{offices.reduce((sum,office)=>sum+office.activeAgents,0)}</strong><span>agent aktif</span></div></section><section className="lobby-toolbar"><div><strong>Office publik</strong><span>{offices.length} sedang dibagikan</span></div><button onClick={()=>void load()}><RefreshCw size={14}/>Refresh</button></section>{loading&&!offices.length?<div className="lobby-empty">Memuat office…</div>:error?<div className="lobby-empty"><Wifi size={22}/><strong>{error}</strong><button onClick={()=>void load()}>Coba lagi</button></div>:!offices.length?<div className="lobby-empty"><Users size={22}/><strong>Belum ada office publik.</strong><span>Owner dapat mengaktifkan tampil di Public Lobby dari pengaturan office.</span></div>:<section className="lobby-grid">{offices.map(office=><a className="lobby-card" href={`/office/${encodeURIComponent(office.slug)}`} key={office.id}><div className="lobby-card-top"><span className="lobby-status"><i/>{office.activeAgents?'Aktif':'Idle'}</span><small>{ago(office.updatedAt)}</small></div><div className="lobby-card-scene"><span className="mini-worker worker-a"/><span className="mini-worker worker-b"/><span className="mini-worker worker-c"/><span className="mini-monitor"/></div><div className="lobby-card-info"><div><h2>{office.displayName}</h2><p>{office.activeAgents} agent aktif · {office.totalAgents} terlihat</p></div><ArrowRight size={17}/></div>{office.agents.length>0&&<div className="lobby-agent-pills">{office.agents.slice(0,4).map(agent=><span key={agent.id}>{agent.name}</span>)}{office.activeAgents>4&&<span>+{office.activeAgents-4}</span>}</div>}</a>)}</section>}<footer className="lobby-footer"><a href="/">Buka office utama</a><span>Public view · read only</span></footer></main>;
}
